### ISSUE TITLE
Wan über WLAN ohne WDS implementieren

### ISSUE THREAD

**Issue by JamesT42** [freifunk-bielefeld/firmware#11]
Hi!
Hab hier so einen Technicolor TC7200 Kabelmodemrouter, der anscheinend weder mit einem TP-Link WA845RE noch mit dem WR841 mit der FF Firmware WDS machen will. Dreckiger Zwangsrouter von Unitymedia halt.
Wan über WLAN ist hier erstmal die einzige Option, ansonsten müsste ich den FF Router in den Keller stellen, und davon kann dann quasi niemand profitieren. Und einen zweiten FF Router dehalb aufstellen ist echt overkill...

**Comment by mwarning** [comment]
Ja, wir wollten das wieder einbauen. Aber z.Z. sind viele Kräfte gebunden andere Probleme zu lösen.
Es fehlt ein freies Wochenende. :)

**Comment by tywunon** [comment]
Gibt es da schon ne Lösung in Aussicht?

Das Problem haben auch alle Fritz.Box Benutzer, da AVM ja den WDS Support eingestellt hat. Würde meinen FF-Router auch gerne mal wieder in Betrieb nehmen.

**Comment by mwarning** [comment]
Noch nicht wirklich. Im Grunde muss nur der WAN Anschluss von einer bridge auf einen einzelnen Anschluss umkonfiguriert werden. Das heißt das in der /etc/config/network der Eintrag "option type bridge'" entfernt werden muss. Das problem ist, das der Name der Interfaces nicht mehr br-wan ist. Der Name ist an vielen Stellen fest mit drin. Vielleicht kann ich das einfach explizit setzen, so als alias.

**Comment by tywunon** [comment]
Ich bin nicht so fit in dem ganzen Unix netzwerk kram, aber könnte das hier helfen?

http://askubuntu.com/questions/27432/configuring-ethernet-network

    mapping eth0
         script /home/<username>/net.sh
         map eth0 eth0-home
         map eth0 eth0-work

    /home/<username>/net.sh
      #!/bin/sh
      echo eth0

müsste man natürlich anpassen...

**Comment by JamesT42** [comment]
Könnte man als workaround die bridge nicht belassen? dann könnte man doch sogar auf dem wan port das "original" wlan durchschleifen und hätte damit noch eine praktische extra funktion.

**Comment by bodems** [comment]
Ein WLAN-Interface im Client-Mode kann man nicht bridgen, siehe hier: http://wiki.openwrt.org/doc/howto/clientmode#bridged_client_mode_issues
Oder meinst du ein zweites WAN-Interface ohne Bridge, aber das alte br-wan beibehalten?

**Comment by mwarning** [comment]
@tywunon: ja, ich überlege soetwas ähnliches als halbwegs elegante Lösung.

**Comment by tywunon** [comment]
firmware 0.5.0 ? *pling* *pling*

**Comment by mwarning** [comment]
@tywunon *ploing* :-) - in der 0.5.0 hat sich dazu noch nichts geändert.

**Comment by tywunon** [comment]
nyo~ron

**Comment by mwarning** [comment]
Feature ist jetzt im development-Entwicklungszweig gefixt und wird dann Teil von 0.5.1.

**Comment by tywunon** [comment]
\o/
