### ISSUE TITLE
TL-WR842ND v2 Switch Einstellungen defekt

### ISSUE THREAD

**Issue by JamesT42** [freifunk-bielefeld/firmware#12]
Tach!
Die  Switch Einstellungen werden für eth0 angezeigt, welches jedoch der WAN Port ist. eth1 ist der LAN Port, wofür es jedoch keine Switch Einstellungen gibt.
Ich würde mal vermuten: das ist das gleiche Problem wie bei den WR841N(D) v8, also wahrscheinlich genau so zu fixen.

**Comment by mwarning** [comment]
ok, danke. Kannst du mal testen ob die Label der Ports passen?? Dann kann ich das direkt mit eintragen.

**Comment by JamesT42** [comment]
was meinst du mit label? also ob port 1 in der firmware mit port 1 auf dem gehäuse übereinstimmt? da weiß ich gerade nicht, wie ich das testen soll.

**Comment by mwarning** [comment]
Ja, genau. Das meine ich. Über die Weboberfläche kannst du z.B. drei der Anschlüsse von LAN auf Freifunk umstellen. Wenn du dann über den verbleibenden Port eine 192.168.133.x Adresse bekommst, dann ist das der eine.
Vielleicht kannst du das Teil gerade bodems geben; der könnte das überprüfen? Cya :-)

**Comment by JamesT42** [comment]
ja mach ich dann so

**Comment by mwarning** [comment]
ok, das hat geklappt. Die Änderungen sind im nächsten Release.

https://github.com/freifunk-bielefeld/firmware/commit/8808e6d9ef5c1b6e577ea0846f17c1c917598105
