### ISSUE TITLE
0.5.0-rc4: Router verliert wan Verbindung

### ISSUE THREAD

**Issue by JamesT42** [freifunk-bielefeld/firmware#13]
HW: WR841ND v9 

verliert einfach zwischendurch die wan Verbindung. 

Ich glaube DHCP lease wird nicht mehr verlängert. bodems hatte so auch keinen Plan. War schon in rc2 so.

**Comment by mwarning** [comment]
Hi James,

hier müsste ich mal einen Setup mit extrem niedrigen lease times aufsetzen. Also einfach mal einen Router dazwischen setzen. Die nächsten Tage sollte ich die nötige Hardware dafür haben.

**Comment by mwarning** [comment]
ok, ich habe mir etwas leihen können. Habe einen Router mit einem DHCP server und sehr kleiner lease time zwischen FF-Router und Modem gepackt.
Der FF-Router hat fleissig seinen lease erneuert. Ich kann das problem soweit nicht reproduzieren.

**Comment by JamesT42** [comment]
Ich kanns auch nicht verstehen... aber in 0.4.4 wars halt nicht.

**Comment by JamesT42** [comment]
Vielleicht hat es auch gar nicht mit DHCP zu tun sondern irgendwas krepelt softwaremäßig ab, sodass der lease nicht verlängert wird. das kannst du so nicht testen mit deinem aufbau.

**Comment by mwarning** [comment]
ist das bei dir immer noch ein problem?

**Comment by JamesT42** [comment]
Ja, ich kapier es auch nicht. Liegt aber anscheinend nicht an FF. Ich hab sogar mit einem v10. Ich bin echt am Ende mit meinem Latein.

**Comment by JamesT42** [comment]
Also wenn, dann ist das ein OpenWRT Problem. Deshalb schließe ich das hier mal.

**Comment by JamesT42** [comment]
Falls es noch jemanden interessiert: https://github.com/openwrt/luci/issues/557

**Comment by mwarning** [comment]
hm, interessant. Da sollten wir mal das mal validieren... morgen :)
