### ISSUE TITLE
UM DS-Lite  MTU Problem

### ISSUE THREAD

**Issue by JamesT42** [freifunk-bielefeld/firmware#14]
Problem: MTU ist bei DS-Lite Anschlüssen reduziert, MTU müsste verringert werden.

https://freifunk-troisdorf.de/probleme-mit-unitymedia-ds-lite-kunden-behoben/

**Comment by mwarning** [comment]
@bodems: also fastd mtu auf 1312 ändern? Wäre schnell gemacht.

**Comment by bodems** [comment]
Ich hab im neuen Mesh für ffbi (bat1 auf vpn1 und vpn6) mal die MTU auf 1312 geändert und bau mal eine Firmware damit.

**Comment by JamesT42** [comment]
Wäre eine andere Lösung die Gateways per ipv6 erreichbar zu machen, dann hätte man das MTU Problem doch nicht bei einer nativen ipv6 Verbindung?

**Comment by L3Dokt0r** [comment]
Wir sind im Jahr 2016. Da wäre es für IPv6 allmählich wirklich mal Zeit. Bei FFBSee haben wir das DS-Lite Problem durch die nutzung von IPv6 umgangen. 

Wenn die Option:

`list remote 'ipv6 "vpn3.freifunk-bielefeld.de" port 1244'`
vor der Option:
`list remote 'ipv4 "vpn3.freifunk-bielefeld.de" port 1244'`
in files/etc/config/fastd steht und die Supernodes IPv6 haben, so baut jeder erstmal eine IPv6 Verbindung auf, wenn der Router und der Server IPv6 haben.
Falls so keine Verbindung zu stande kommt wird IPv4 verwendet.

**Comment by mwarning** [comment]
@L3Dokt0r das konnte in Bielefeld bisher nicht gemacht werden, da nicht alle Server ipv6 Anbindung hatten. Das führte zu einer sehr ungleichen Verteilung der Knoten.
@bodems: haben jetzt alle Server öffentliche IPv6 Adressen?

**Comment by JamesT42** [comment]
Ich denke mit der aktuellen Config, dass die Gateways über ipv6 erreichbar sind sollte es keine MTU Probleme mehr mit Unitymedia gebe.
