### ISSUE TITLE
Bessere ipv6 Unterstützung

### ISSUE THREAD

**Issue by JamesT42** [freifunk-bielefeld/firmware#16]
Hi!
Ich fände es gut, wenn die Gateways auch nativ über ipv6 erreichbar sind. Eventuell können wir uns damit die Reduzierung der MTU sparen, da die DS-Lite Anschlüsse ja nativ ipv6 beherrschen.

**Comment by hauetaler** [comment]
Wenn die IPv6- und IPv4-Adressen der Gateways im DNS eingetragen sind, sollte das doch damit zu erschlagen sein, oder?

**Comment by JamesT42** [comment]
dafür müsste in den fastd optionen noch das "ipv4" gestrichen werden

**Comment by lroller** [comment]
Bei Freifunk Bodensee haben wir das Problem mit den DS-Lite Anschlüssen gelöst, dass erst die Verbndung mit IPv6 versucht wird und danach die Verbindung für ipv4 steht:

[/files/etc/config/fastd](https://github.com/ffbsee/firmware/blob/master/files/etc/config/fastd)

So verbinden sich alle Anschlüsse ohne ipv6 problemlos und Anschlüsse mit ipv6 nutzen IPv6, was ja auch nicht schlecht ist.

**Comment by mwarning** [comment]
@lroller danke für die Info. Ich dachte die Reihenfolge in der fastd config Datei hätte keine Auswirkung.

**Comment by JamesT42** [comment]
Ich hab jetzt seit ein paar Wochen einen Router an einem DS-Lite Anschluss getestet indem ich alles auf "ipv6" umgeändert habe. Bisher keine Probleme. Soll das eventuell mal implementiert werden? Oder wenigstens in der GUI einschaltbar sein für Unitymedia-dslite-geschädigte?

**Comment by mwarning** [comment]
@JamesT42 Ein Umschalten auf ipv6 wäre wir lieber. Aber dann wäre es blöd wenn Leute dennoch probleme haben. Das dürften z.Z. vorallem noch Leute sein, die einen FF-Router hinter ihrem heimrouter und NAT laufen lassen.

**Comment by JamesT42** [comment]
@mwarning wie im chat besprochen hat ipv6 unterstützung erstmal nichts mit dem mtu problem zu tun :)
aber nun die frage: soll das so wie bei ff bodensee gemacht werden mit jeweils zwei einträgen oder soll jeweils das "ipv4" weggelassen werden? ich weiß nicht was besser ist.

**Comment by L3Dokt0r** [comment]
@JamesT42 Bei FFBSee haben wir mitlerweile die Optionen zum auswählen: IPv4, IPv6 oder DualStack(Standard).


`set_ipv6_only(){`

`	local ipv6_only="$(uci get -q freifunk.@settings[0].ipv6_only 2> /dev/null)"`
	
	if [ "$ipv6_only" = "ipv6" ]; then
                if !(grep "#list remote 'ipv4" /etc/config/fastd); then sed -i "s/list remote 'ipv4/#list remote 'ipv4/g" /etc/config/fastd; fi
                if (grep "#list remote 'ipv6" /etc/config/fastd); then sed -i "s/#list remote 'ipv6/list remote 'ipv6/g" /etc/config/fastd; fi
	fi
	if [ "$ipv6_only" = "both" ]; then
		if (grep "#list remote 'ipv4" /etc/config/fastd); then sed -i "s/#list remote 'ipv4/list remote 'ipv4/g" /etc/config/fastd; fi
                if (grep "#list remote 'ipv6" /etc/config/fastd); then sed -i "s/#list remote 'ipv6/list remote 'ipv6/g" /etc/config/fastd; fi
	fi
        if [ "$ipv6_only" = "legacy" ]; then
                if (grep "#list remote 'ipv4" /etc/config/fastd); then sed -i "s/#list remote 'ipv4/list remote 'ipv4/g" /etc/config/fastd; fi
                if !(grep "#list remote 'ipv6" /etc/config/fastd); then sed -i "s/list remote 'ipv6/#list remote 'ipv6/g" /etc/config/fastd; fi
        fi
`} `
[FFBSee](https://github.com/ffbsee/firmware/blob/master/files/etc/init.d/freifunk_init)

**Comment by mwarning** [comment]
@L3Dokt0r danke für den Input. Ich vermute das es bei fastd eine option gibt, um zwischen ipv4/ipv6 zu wechseln.  Das habe ich aber noch nicht nachgeschaut.

**Comment by L3Dokt0r** [comment]
Wir haben so jedenfalls den IPv4 oder IPv6 eintrag auskommentiert wenn die entsprechende Option in der Freifunk Config gesetzt ist.

**Comment by JamesT42** [comment]
Sollten wir wohl noch einen manuellen override einbauen?

**Comment by mwarning** [comment]
@JamesT42 ich glaube das ist nciht nötig. Das mtu Problem ist ja jetzt gelöst meine ich.
