### ISSUE TITLE
Keine Kartendaten und fehlende Infos in der Web-GUI

### ISSUE THREAD

**Issue by bodems** [freifunk-bielefeld/firmware#38]
Es werden anscheinend keine oder zu wenig Informationen für die Karte übertragen. Obwohl in der Web-GUI"alles" ausgewählt ist, erscheint ein Knoten nur mit seiner MAC im Meshviewer, der Name wird nicht übertragen.
Der Knotenname wird zwar auf der Statusseite angezeigt, aber nicht im entsprechenden Feld nach dem Login. Dort fehlt auch die Anzeige des verfügbaren Flashspeichers.

**Comment by mwarning** [comment]
Sollte hiermit gefixt sein: https://github.com/freifunk-bielefeld/firmware/commit/af2378c9e4527a9594211e66ddd2f5f9b6126490

**Comment by mwarning** [comment]
fixed
