### ISSUE TITLE
Support für aktuelle Hardware

### ISSUE THREAD

**Issue by cknost** [freifunk-bielefeld/firmware#41]
Mir fehlt ein Openwrt Update mit Support für aktuelle Router wie dem Archer C50 v4.

Der Support für das Modell C50 v4 wurde hier hinzugefügt: https://github.com/openwrt/openwrt/commit/01dcd574a24864c10a9c4df4304a3ce0da5c11a9
Ich habe bereits das Image einer anderen Freifunk-community mit diesem Modell getestet und konnte keine Probleme feststellen: https://forum.freifunk.net/t/tp-link-ac1200-archer-c50-ver-4-0/20452/7

**Comment by cknost** [comment]
Ich habe einen Fork erstellt und kann die Firmware nun mit dem Archer c50 v4 nutzen.

**Comment by mwarning** [comment]
hi, danke für das testen.
Wir haben leider alle wenig Zeit und haben kaum/keine Zeit für das Projekt. Obwohl ich natürlich noch hoffe, doch noch Motivation und Zeit aufzubringen um die Firmware auf den Stand von github/ffulm/firmware zu bringen.
