### ISSUE TITLE
Build funktioniert nicht mehr

### ISSUE THREAD

**Issue by cknost** [freifunk-bielefeld/firmware#44]
Unter Manjaro lässt sich die Firmware nicht mehr bauen.
ich denke, das liegt an folgendem Bug: https://github.com/openwrt/openwrt/commit/05062462f12952dba47c2c4529a179576e4a4fd9

**Comment by cknost** [comment]
Die betrifft auch das Development Branch

**Comment by cknost** [comment]
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-basic', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-basic', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-p2p', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpa-supplicant-wolfssl||', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-basic', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_hostapd-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mesh-wolfssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-basic', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-mini', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-openssl', which does not exist
WARNING: Makefile 'package/network/services/hostapd/Makefile' has a dependency on 'PACKAGE_wpad-wolfssl||', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-https-dns-proxy/Makefile' has a dependency on 'https-dns-proxy', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-ksmbd/Makefile' has a dependency on 'ksmbd-server', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-vpn-policy-routing/Makefile' has a dependency on 'vpn-policy-routing', which does not exist
WARNING: Makefile 'package/feeds/packages/python-zipp/Makefile' has a dependency on 'python3-more-itertools', which does not exist
tmp/.config-package.in:132106: syntax error
tmp/.config-package.in:132105: invalid option
tmp/.config-package.in:136724: syntax error
tmp/.config-package.in:136723: invalid option
make: *** [/home/clemensk/freifunk/openwrt/include/toplevel.mk:142: menuconfig] Fehler 1

**Comment by mwarning** [comment]
Ich kann das Problem leider nicht reproduzieren.
Das Installationsmedium war manjaro-gnome-18.1.5-191229-linux54.iso.
Ich habe vor dem Bauen eine Reihe von Abhängigkeiten installiert. Die Liste habe ich aber gerade nicht mehr.

**Comment by mwarning** [comment]
Ok, auf meinem Host-System (Void Linux) ist das Problem aufgetreten. :-)
Der patch hat geholfen. Ich habe es mal hinzugefügt:
<strike>https://github.com/freifunk-bielefeld/firmware/commit/11d80718db02a8e5c4db6ebb33f25075049bfa4c</strike> https://github.com/freifunk-bielefeld/firmware/commit/86be364a0163df5b05cab390b88d76a2cb16799a

Kannst du mal testen ob das bei dir jetzt auch geht? Danke!

**Comment by cknost** [comment]
Ja, Funktioniert wieder.
